# Generated by Django 4.1.1 on 2022-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('C', 'Csutomer'), ('S', 'Seller')], default='C', max_length=1),
        ),
    ]
