version: "3.8"

services:
    db_pg:
      image: postgres:alpine3.17
      restart: always
      container_name: auto_marketplace
      environment:
          POSTGRES_DB: "${DB_NAME}"
          POSTGRES_USER: "${DB_USER}"
          POSTGRES_PASSWORD: "${DB_PASSWORD}"
          PGDATA: "${DB_PGDATA}"
      volumes:
          - ./data/postgres:/var/lib/postgresql/data/
      ports:
          - "5432:5432"

    backend:
      build: .
      restart: always
      ports:
        - 8000:8000
      depends_on:
        - db_pg