# Generated by Django 4.1.1 on 2022-10-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product_id',
            new_name='product',
        ),
    ]
