# Generated by Django 4.1.1 on 2022-10-31 14:46

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_product_id_shoppingcart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=goods.models.user_directory_path, verbose_name='Product Image'),
        ),
    ]
