# Generated by Django 4.1.1 on 2022-11-01 13:03

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_owner_product_user_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=goods.models.category_directory_path, verbose_name='Category Image'),
        ),
    ]
