# Generated by Django 4.1.1 on 2022-11-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_currencyrate_product_price_euro_product_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
