# Generated by Django 4.1.1 on 2022-11-15 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_remove_product_currency_remove_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={"get_latest_by": "updated"},
        ),
    ]
