# Generated by Django 4.1.1 on 2022-10-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_modiration',
            new_name='on_moderation',
        ),
    ]
