# Generated by Django 4.1.1 on 2022-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
